[project]
name = "api"
version = "0.1.0"
description = "Portfolio RAG API backend"
readme = "README.md"
authors = [
    { name = "Noel Schwabenland", email = "noel@schwabenland.ch" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["api"]
